### ISSUE TITLE
Test: Model State tracking

### ISSUE THREAD

**Issue by manuGil** [openearth/aeolis-python#103]
We need to implement tests for the following scenario:

## Description
Tests that class ModelState set model variable correctly
## Code reference
https://github.com/openearth/aeolis-python/blob/0596eef57f1a69946698cd0a4fdcb719411f0a1c/aeolis/model.py#L86-L91
### Case 1: The model state should be initialized with a set of immutable variables

- **Preconditions:** a variable number of args and kwargs
- **Test Steps:** 
     - Create an instance of ModelState by passing a number of args and kwargs
- **Expected Result:** initialized instance of ModelState with an empty set of immutable variables
- **Postcondition:** A instance of ModelState is created 

### Case 2: Add and update state variable  and their values 
- **Preconditions:**  An instance of ModelState has been successfully initialised
- **Test Steps:** 
    - Initialize an instance of ModelState
    - Add a new variable and value to the set of immutable variables
    - Change the value of the existing mutable state variable
- **Test Data:**  variable name and value
- **Expected Result:** model variable is either added or updated 
- **Postcondition:** Instance of ModelState contains new state variable or value
    
### Case 3: set existing state variable as mutable
- **Preconditions:** An instance of ModelState has been successfully initialised with at least one state variable
- **Test Steps:** 
    - Initialize an instance of ModelState
    - call set_mutable() to change variable condition in  ModelState
    - check if the new variable was added to the set of mutable variables
- **Test Data:** name for state variable
- **Expected Result:** state variable is added to the mutable set
- **Postcondition:** state variable of and instance of ModelState is set to mutable

### Case 4:  set existing state variable as immutable
- **Preconditions:** An instance of ModelState has been successfully initialised, with at least one mutable state variable
- **Test Steps:** 
    - Initialize an instance of ModelState
    - call set_immutable() to change state variable condition in  ModelState
    - check if the variable was removed from the set of mutable variables
- **Test Data:** name for muttable state variable
- **Expected Result:** state variable is removed from the mutable set
- **Postcondition:** state variable of an instance of ModelState is set to immutable

**Comment by niketagrawal** [comment]
Fixed with #112
