### ISSUE TITLE
Readthedocs does not display model.py in the overview of model code.

### ISSUE THREAD

**Issue by Sierd** [openearth/aeolis-python#146]
https://aeolis.readthedocs.io/en/latest/_modules/index.html 

I am missing a link to 'model'. Maybe other modules are not displayed neither.

**Comment by manuGil** [comment]
The list of modules in this index is controlled by the references in `sourcecode.rst` I will check all the modules are included there and this should be fixed in the next pull request.
My local version of the documentation (not yet in RTD) lists the model module:

![Screenshot from 2023-08-09 11-30-07](https://github.com/openearth/aeolis-python/assets/8195424/a067eb4a-4b4b-4fb1-815a-6e276fce0514)

**Comment by manuGil** [comment]
This is the current list of modules in Aeolis. @bartvanwesten  Is this version of the console of general use? If yes, can you let me know what is the purpose? I would like to write a description in the documentations. https://github.com/openearth/aeolis-python/blob/0b4133e96918be29ce0049ab86b6539844acef61/aeolis/console_debug.py#L1

![Screenshot from 2023-08-09 11-46-38](https://github.com/openearth/aeolis-python/assets/8195424/e1fe1541-c5e5-4e11-927b-ba299a191b06)

**Comment by manuGil** [comment]
> The list of modules in this index is controlled by the references in `sourcecode.rst` I will check all the modules are included there and this should be fixed in the next pull request. My local version of the documentation (not yet in RTD) lists the model module:
> 
> ![Screenshot from 2023-08-09 11-30-07](https://user-images.githubusercontent.com/8195424/259362923-a067eb4a-4b4b-4fb1-815a-6e276fce0514.png)

The `constants.py` module does not contain common python code and docstrings (functions or classes), therefore it is not worth including it.

**Comment by manuGil** [comment]
@Sierd  What is the purpose of the `gridparams.py` module? 
https://github.com/openearth/aeolis-python/blob/0b4133e96918be29ce0049ab86b6539844acef61/aeolis/gridparams.py#L37-L54

**Comment by manuGil** [comment]
The `run_console.py` contains a reference to a remote drive. Is this file relevant to the documentation?

https://github.com/openearth/aeolis-python/blob/main/aeolis/run_console.py

**Comment by Sierd** [comment]
@manuGil the `run_console.py` script provides a way to run the model inside a python environment (like in vscode or spyder) . This is convenient for debugging while it is impossible to use breakpoints when running from the command line you can use this script instead running the console but then in the python environment. I consider it a helper function. The reference to the external path is related to the input file. This is different for every computer that it is used on. It is not pretty but it works while developing code. 

Th `gridparams.py` file has only one function. The initialization of the grid and a check if the grid is properly defined. Based on the x and y input files some basic grid related dimensions are initialized like grid distance and grid surface. These parameters are broadcasted to the s-dictionary for use by other modules.

**Comment by manuGil** [comment]
Thank you @Sierd  I added descriptions to the modules and included them in the documentation. The changes will be in the next PR
