### ISSUE TITLE
Add developer documentation on software testing and code development workflow

### ISSUE THREAD

**Issue by niketagrawal** [openearth/aeolis-python#148]
Write documentation for developers containing guidelines and getting started information on:
- Code development workflow, code style
- Software testing: concepts and how to write tests

**Comment by niketagrawal** [comment]
Changes are being developed in the feature branch [docs](https://github.com/openearth/aeolis-python/tree/docs)

**Comment by manuGil** [comment]
I am reviewing the docs on test, and making some changes.

**Comment by niketagrawal** [comment]
Changes added via #136
