### ISSUE TITLE
Implement examples as part of the CLI

### ISSUE THREAD

**Issue by manuGil** [openearth/aeolis-python#158]
We can't pack data about the examples with the package so that users can easily set up and run examples via the CLI.

For example, the following command should create a directory with the example's data in the current directory:

```shell
aeolis examples
```
## Expected result:

Users see an `aeolis-ex` directory containing subdirectories with config files that can be run as any AeoLiS model.

**Comment by manuGil** [comment]
@niketagrawal  Can you let me know which two of the cases in the tests directory we should include in this feature?

**Comment by manuGil** [comment]
The parser used for the CLI has yet to be updated since 2014: https://pypi.org/project/docopt/#history. I suggest updating to a more modern parser. This will be very easy because the current CLI only has two commands.

**Comment by niketagrawal** [comment]
> @niketagrawal Can you let me know which two of the cases in the tests directory we should include in this feature?

@manuGil, the examples with links to the model configuration files are below:

1. [2D parabolic dune](https://github.com/openearth/aeolis-python/tree/main/examples/2D/Parabolic_dune)
2. [Sandmotor](https://github.com/openearth/aeolis-python/tree/parallell_update/examples/sandengine_small_grids): Remove the keyword `parallel = T` from aeolis.txt file.

**Comment by manuGil** [comment]
> > @niketagrawal Can you let me know which two of the cases in the tests directory we should include in this feature?
> 
> @manuGil, the examples with links to the model configuration files are below:
> 
> 1. [2D parabolic dune](https://github.com/openearth/aeolis-python/tree/main/examples/2D/Parabolic_dune)
> 2. [Sandmotor](https://github.com/openearth/aeolis-python/tree/parallell_update/examples/sandengine_small_grids): Remove the keyword `parallel = T` from aeolis.txt file.

@niketagrawal Could we be consistent with the use of CAPS in the naming of examples? It is not a must, but I think it will help to have everything to small caps, in the long run

**Comment by niketagrawal** [comment]
> > > @niketagrawal Can you let me know which two of the cases in the tests directory we should include in this feature?
> > 
> > 
> > @manuGil, the examples with links to the model configuration files are below:
> > 
> > 1. [2D parabolic dune](https://github.com/openearth/aeolis-python/tree/main/examples/2D/Parabolic_dune)
> > 2. [Sandmotor](https://github.com/openearth/aeolis-python/tree/parallell_update/examples/sandengine_small_grids): Remove the keyword `parallel = T` from aeolis.txt file.
> 
> @niketagrawal Could we be consistent with the use of CAPS in the naming of examples? It is not a must, but I think it will help to have everything to small caps, in the long run

Yes, PEP8 style guide also recommends using all lowercase for naming directories.

**Comment by manuGil** [comment]
copying this to main branch and removing the `parallel = T` : [Sandmotor](https://github.com/openearth/aeolis-python/tree/parallell_update/examples/sandengine_small_grids): Remove the keyword parallel = T from aeolis.txt file.

**Comment by niketagrawal** [comment]
Fixed with #160
