### ISSUE TITLE
streamline 1d/2d implementation of processes

### ISSUE THREAD

**Issue by Sierd** [openearth/aeolis-python#190]
We plan to make a quasi 2D version of any 1D model to overcome issues with the current 1D approaches.

**Comment by CarolineHalllin** [comment]
Good idea!

**Comment by Sierd** [comment]
thanks

**Comment by Sierd** [comment]
We chose to make a change on the level of the initialization of the model.
This seems to work for a 1D model without bed level changes and vegetation.

We should look of additional input files need an update too.

https://github.com/openearth/aeolis-python/blob/ba69df0fd9373975bbcf4a95f07d9971b10c2f5e/aeolis/model.py#L201C13-L215C30
