### ISSUE TITLE
Model simulation run for 1D case3_erosion_avalanching fails because of Keyerror 'Cs'

### ISSUE THREAD

**Issue by niketagrawal** [openearth/aeolis-python#225]
### Steps to reproduce the issue
- Check out the main branch
- Run the example 1D/case3_erosion_avalanching by executing `aeolis run aeolis/examples/1D/case3_erosion_avalanching/aeolis.txt` from the root of the repository. 
- The above command fails with the below error on the console pointing to a line in erosion.py
```
File "/~/aeolis-python/aeolis/erosion.py", line 94, in run_ph12
    Cs = p['Cs']
         ~^^^^^^

KeyError: 'Cs'
```

The error is only observed from the commit https://github.com/openearth/aeolis-python/commit/acb445281b4d7507280b60825bd1ecf8ac227201 onwards.

**Comment by Sierd** [comment]
@niketagrawal I fixed this by introducing Cs as a variable. We can test this in the [fix-226-regression-tests](https://github.com/openearth/aeolis-python/tree/fix-226-parametrize-regression-tests) and close this issue.
