### ISSUE TITLE
Shear solver instabilities 

### ISSUE THREAD

**Issue by maddykelley** [openearth/aeolis-python#227]
After chatting with Bart, I believe we identified an issue with the shear solver. Instabilities appear in the first few timesteps. In this example, the wind magnitude changes, but the direction remains constant. I noticed the same issue in other test runs on the fluvial-aeolian discussion board as well. I’m fairly confident that I need to use the 'shear processes' to produce the correct erosion/deposition patterns linked to topographic effects.

![image](https://github.com/user-attachments/assets/9f22b7f9-f606-4943-83eb-3d513f4a79c4)
![image](https://github.com/user-attachments/assets/5505c680-1cd0-4a54-93be-991e548782f3)
![image](https://github.com/user-attachments/assets/687ae12b-2bed-4218-ae64-7ba5dcf7aae2)

I've attached all my input files. I can email the output files (too large to upload)
[input.zip](https://github.com/user-attachments/files/16898013/input.zip)

Bart, am I missing any important info?

**Comment by bartvanwesten** [comment]
The shear solver seems to have some issues with your current topography. A more detailed answer is given in Discussion #219

**Comment by Sierd** [comment]
I close this issue because of the ongoing discussion about this here #219
