### ISSUE TITLE
attempt to install AeoLiS V2, but the "vegetation.py" file in the installed package is not V2.

### ISSUE THREAD

**Issue by lzhu5** [openearth/aeolis-python#29]
Hi, 

I installed AeoLiS V2.0 in an anaconda virtual environment using "python setup.py install". After installation, I checked the python files in the installed package, which is located in "/opt/anaconda3/envs/aeolis_v3/lib/python3.9/site-packages/AeoLiS-2.0.0.dev2-py3.9.egg/aeolis/". I found that for "vegetation.py", the code is not what I saw in V2.0 because it still uses p['dt'] to update s['hveg'] as below:
s['hveg'] += s['dhveg']*(p['dt'] * p['accfac']) / (365.25*24.*3600.)

The other lines are different from V2.0 too. 

Also, I tried to add a print line (like print('test')) in the source code "vegetation.py" and install AeoLiS again. This time, I found that the "vegetation.py" in the installed package is the same as in V2.0 (because s['hveg'] += s['dhveg']*(p['dt_opt'] * p['accfac']) / (365.25*24.*3600.)). However, when I ran "aeolis aeolis.txt", I received an KeyError: 'dt_opt'. 
 
Would you please suggest how to use the latest version?  Thanks.

Best,
Ling Zhu

**Comment by ncohn** [comment]
Hey Ling,
We are just wrapping up a big development push over the last few weeks -
which is the reason for a v2 update, although it really should still be
considered a dev branch. The last changes Bart pushed for 2D grid rotation
dont entirely work with 1D. Thats my goal to address in the next ~week. I
can update you when the 1D/2D compatibility issues are solved.
-Nick

**Comment by lzhu5** [comment]
Hi Nick, Thanks for letting me know. Looking forward to V2.0.  -Ling

**Comment by ncohn** [comment]
Hey Ling, We havent fully release v2.0 yet, but do have a release that
seems to be stable/working for 1D cases now if you are eager to try it. Can
use "pip install AeoLiS==2.0.0.dev4" to automatically download that
version. Note that there are some additional keynames now, so you may be
interested in starting by looking at the 1D or 2D templates in the
"examples" folder on GitHub. Let us know if you have any issues with this!
-Nick

**Comment by lzhu5** [comment]
Hi Nick,

It is great. I will try the dev release and check those new parameters. I will let you know how it goes.

(BTW, in vegetation.py (Line 258), "vegfac" should be applied to "ustar" instead of "tau", because "vegfac" is already the sqrt of shear stress ratio.)

-Ling

**Comment by manuGil** [comment]
@CarolineHalllin and @lzhu5 Can I close this issue?

**Comment by lzhu5** [comment]
Yes.
