### ISSUE TITLE
Unwanted directories in default branch

### ISSUE THREAD

**Issue by manuGil** [openearth/aeolis-python#33]
The default branch has [unwanted directories](https://github.com/openearth/aeolis-python/tree/AEOLIS_V2/.idea) (.idea) in it. Such directories usually hold user configurations for IDEs like Pycharm, and they are not relevant to the source code. They often only clutter the repository. We should remove them.

**Comment by Sierd** [comment]
Agreed! Lets remove those.
@ncohn  could you confirm deleting the .idea directory?
