### ISSUE TITLE
What is the purpose of the dist directory?

### ISSUE THREAD

**Issue by manuGil** [openearth/aeolis-python#34]
The [dist directory](https://github.com/openearth/aeolis-python/tree/AEOLIS_V2/dist) contains an 'egg' of the source code. However, usually compiled code should be distributed via pyPIP. What purpose does the content of this directory serve?

**Comment by Sierd** [comment]
I expect the dist directory has accidentally been created while uploading code of a local installation. I expect it can be deleted.

**Comment by manuGil** [comment]
> I expect the dist directory has accidentally been created while uploading code of a local installation. I expect it can be deleted.

Alright, I will go ahead and delete it, I will also clean some of the IDE-specific configuration folders.

**Comment by manuGil** [comment]
Resolved in #54
