### ISSUE TITLE
Duplicated README files

### ISSUE THREAD

**Issue by manuGil** [openearth/aeolis-python#36]
There are two README files in the repository with different information. It would be better to consolidate the information in a single file. Can we move the text from [README.rst](https://github.com/openearth/aeolis-python/blob/AEOLIS_V2/README.rst) to README.md?

**Comment by Sierd** [comment]
I remember that these readme files used to serve different purposes. Readme.md is read and displayed by Github. Readme.rst is read and displayed as the project description on the pypi website. Merging them would make sense.

**Comment by manuGil** [comment]
Addressed in #125
