### ISSUE TITLE
Are these two repos about Aeolis related and active?

### ISSUE THREAD

**Issue by manuGil** [openearth/aeolis-python#40]
Openearth has two repositories with source code for Aeolis:

1. This one, and
2. https://github.com/openearth/aeolis

- **Are the repositories related?** 
- **Is the second repository active?** If not, we should archive it so that it is clear to potential contributors which repository is for development.

**Comment by Sierd** [comment]
I don't believe the second repository is active anymore. The second repository is a remnant of a time that we experimented with different code languages. In the second repository there is mostly FORTRAN code. In 2015 we decided to focus on the python language and therefore we have started the aeolis-python repository. OK to archive the 2nd repository.
