### ISSUE TITLE
The size of the y input file should not matter for 1D cases

### ISSUE THREAD

**Issue by GlennStrypsteen** [openearth/aeolis-python#56]
In this code uwn is set to zero when the size of the y input file is equal to zero. This means that your shear velocity is calculated too low and thus underestimating sediment transport.

```
if p['ny'] == 0:
        s['uwn'][:,:] = 0.
```

**Comment by GlennStrypsteen** [comment]
Removed these two lines to solve this issue.

**Comment by niketagrawal** [comment]
Closed with pull request #63
