### ISSUE TITLE
purpose of th_drylayer?

### ISSUE THREAD

**Issue by Sierd** [openearth/aeolis-python#74]
There is no documentation at this function. 

https://github.com/openearth/aeolis-python/blob/73eb59745569bd7eab65bbd4792b6c7fc7cc0b53/aeolis/threshold.py#L241

What does it do? Why should it be used?

**Comment by bartvanwesten** [comment]
It is "temporary" implementation to reproduce the decaying erosion from the bed in the supratidal zone (i.e. due to moisture). A solid solution could be implemented instead as a replacement or, even better, include the processes potentially causing it. I will remove the function for now.
